services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  BeFlo\T3Elasticsearch\:
    resource: '../Classes/*'

  cache.t3_elasticsearch_cache:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['t3_elasticsearch_cache']

  BeFlo\T3Elasticsearch\Server\ServerLoader:
    arguments:
      $indexLoader: '@BeFlo\T3Elasticsearch\Index\IndexLoader'

  BeFlo\T3Elasticsearch\Domain\Dto\Server:
    autowire: false

  BeFlo\T3Elasticsearch\Index\Index:
    autowire: false

  BeFlo\T3Elasticsearch\Mapping\Mapping:
    autowire: false

  BeFlo\T3Elasticsearch\Configuration\ConfigurationManager:
    arguments:
      $serverLoader: '@BeFlo\T3Elasticsearch\Server\ServerLoader'
      $cache: '@cache.t3_elasticsearch_cache'

  BeFlo\T3Elasticsearch\Backend\ToolbarItems\ElasticSearchToolbarItem:
    arguments:
      $configurationManager: '@BeFlo\T3Elasticsearch\Configuration\ConfigurationManager'

  BeFlo\T3Elasticsearch\Service\TableFieldAnalyzerService:
    arguments:
      $languageService: '@TYPO3\CMS\Core\Localization\LanguageService'

  _instanceof:
    BeFlo\T3Elasticsearch\Hook\Interfaces\BaseHookInterface:
      tags: [ 't3_elasticsearch.hook' ]

  BeFlo\T3Elasticsearch\Service\HookService:
    arguments: [ !tagged t3_elasticsearch.hook ]
    public: true